/**
 * Seller Model
 * -----------------
 * This file defines the Sequelize `Seller` model, which represents the `seller` table in the database.
 *
 * Contains:
 * - Model attributes (`SellerAttributes`).
 * - Attributes required for creation (`SellerCreationAttributes`).
 * - Model definition with its columns and constraints.
 *
 * This model is used by services and controllers to perform CRUD operations for sellers.
 */
import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";

/**
 * Main attributes of the `seller` entity.
 */
export interface SellerAttributes {
    id_seller: number;
    access_id: number;
    gender_id: number;
    fullname: string;
    phone?: string | null;
    email: string;
    birth_date: Date;
    is_active: boolean;
}

/**
 * Attributes used for creating a new seller.
 * `Optional` is used to indicate that `id_seller` is not required at the time of creation, as it is automatically generated by the database.
 */
export interface SellerCreationAttributes extends Optional<SellerAttributes, "id_seller"> { }

/**
 * Class that represents the `seller` model in Sequelize.
 * 
 * Implements the attributes defined in `sellerAttributes` and `sellerCreationAttributes`.
 */
class Seller extends Model<SellerAttributes, SellerCreationAttributes> implements SellerAttributes {
    public id_seller!: number;
    public access_id!: number;
    public fullname!: string;
    public phone!: string | null;
    public email!: string;
    public birth_date!: Date;
    public gender_id!: number;
    public is_active!: boolean;
}

/**
 * Initialization of the `Seller` model with the Sequelize configuration.
 *
 * - `id_seller`: Auto-incrementing integer, primary key.
 * - `access_id`: Foreign key to the access table.
 * - `fullname`: Seller's full name, up to 100 characters.
 * - `phone`: Seller's phone number (optional).
 * - `email`: Unique email address of the seller.
 * - `birth_date`: Seller's date of birth.
 * - `is_active`: Boolean to determine whether the seller is active or inactive.
 */
Seller.init(
    {
        id_seller: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true,
        },
        access_id: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: "access",
                key: "id_access",
            },
        },
        fullname: {
            type: DataTypes.STRING(100),
            allowNull: false,
        },
        phone: {
            type: DataTypes.STRING(20),
            allowNull: true,
        },
        email: {
            type: DataTypes.STRING(100),
            allowNull: false,
            unique: true      
        },
        birth_date: {
            type: DataTypes.DATE,
            allowNull: false,
        },
        gender_id: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: "gender",
                key: "id_gender",
            },
        },
        is_active: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: true,
        }
    },
    {
        sequelize,
        modelName: "Seller",      // Model name in Sequelize
        tableName: "seller",    // Name of the table in the database (singular)
        timestamps: true,      // includes createdAt and updatedAt
        createdAt: "created_at",
        updatedAt: "updated_at"
    }
);

export default Seller;
